# Site settings
title: Zixiang Zhao
description: A simple Jekyll blog theme developed by Zixiang Zhao 
url: "https://zhaozixiang1228.github.io/" # the base hostname & protocol for your site, e.g. http://example.com

# Author settings
author:
  name     : Zixiang Zhao
  bio      : My name is Zixiang Zhao. I am currently a second year MPhil student at Xi'an Jiaotong University, supervised by Prof. Jiangshe Zhang. I obtained my Bachelor's degree from Northwest University in China. My current research interests are in computer vision and image fusion. I am expected to obtain my Master's degree in 2021 and purse an admission of a PhD program in the area of deep learning and computer vision.
  email    : zixiangzhao@stu.xjtu.edu.cn
#  twitter  : https://twitter.com/mateussousam

#SEO settings
logo: /assets/img/img-blog.png/ # Site logo URL
twitter_username: mateussousam # Twitter username
facebook:
    app_id: 1445035275808959 # App ID
    publisher: https://www.facebook.com/mateus.sousamedeiros # URL of the Facebook page
    admins: 100000229048939 # Facebook user ID that manages the page

# Build settings
permalink: /:title/
markdown: kramdown
paginate: 5
paginate_path: "/blog/page/:num"

gems:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-seo-tag

exclude:
  - Gemfile
  - Gemfile.lock

css_folder:  "/assets/css"
js_folder:  "/assets/js"
img_folder:  "/assets/img"
sass:
    style: compressed